### ISSUE TITLE
LWRP not working as stated on the README

### ISSUE THREAD

**Issue by aalmenar** [chr4-cookbooks/iptables-ng#63] opened 2016-10-06 16:07 UTC
Hi,

I've been trying to use this cookbook following the documentation. I have on my recipe, somethign like this:

```ruby
include_recipe 'iptables-ng::install'

iptables_ng_chain 'INPUT' do
  policy 'DROP [0:0]'
end

iptables_ng_rule 'ssh' do
  rule '--protocol tcp --dport 22 -j ACCEPT'
end
```

But Default policy on filter table on INPUT chain is always ACCEPT. Tried also this:

```ruby
iptables_ng_chain 'INPUT' do
  policy 'DROP [0:0]'
  table 'filter'
  chain 'INPUT'
end
```

But no result, even tried this:

```ruby
iptables_ng_chain 'default' do
  policy 'DROP [0:0]'
  table 'filter'
  chain 'INPUT'
end
```

But also, no results.

Should policies be configured on attributes and not using LWRP's ?

Cheers.

Edit (chr4): Added syntax highlighting

**Comment by chr4** [comment] 2016-10-06 16:18
Thanks for reporting!

```ruby
iptables_ng_chain 'INPUT' do
  policy 'DROP [0:0]'
end
```

Is the correct way of doing it. The recommended way of configurating iptables (incl. policies) are the LWRPs, it's supposed to be working the way you are doing this.

Can you provide some more information? Helpful would be the OS/ Version you're using plus:

```
sudo tree /etc/iptables.d
```

Plus the content generated iptables rulefiles, on Debian/ Ubuntu they are located in `/etc/iptables/rules.*`.

**Comment by aalmenar** [comment] 2016-10-06 16:38
Sure:

OS: Ubuntu 16.04 (amd64) but Debian 8.6 (amd64) happens the same.

# Generated by iptables-save v1.6.0 on Thu Oct  6 16:32:07 2016
*mangle
:PREROUTING ACCEPT [127:9900]
:INPUT ACCEPT [127:9900]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [80:9157]
:POSTROUTING ACCEPT [80:9157]
COMMIT
# Completed on Thu Oct  6 16:32:07 2016
# Generated by iptables-save v1.6.0 on Thu Oct  6 16:32:07 2016
*nat
:PREROUTING ACCEPT [2:84]
:INPUT ACCEPT [2:84]
:OUTPUT ACCEPT [3:292]
:POSTROUTING ACCEPT [3:292]
COMMIT
# Completed on Thu Oct  6 16:32:07 2016
# Generated by iptables-save v1.6.0 on Thu Oct  6 16:32:07 2016
*raw
:PREROUTING ACCEPT [127:9900]
:OUTPUT ACCEPT [80:9157]
COMMIT
# Completed on Thu Oct  6 16:32:07 2016
# Generated by iptables-save v1.6.0 on Thu Oct  6 16:32:07 2016
*filter
:INPUT ACCEPT [12:871]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [80:9157]
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
COMMIT
# Completed on Thu Oct  6 16:32:07 2016

The output of tree /etc/iptables.d

/etc/iptables.d
|-- filter
|   |-- FORWARD
|   |   `-- default
|   |-- INPUT
|   |   |-- default
|   |   |-- ssh.rule_v4
|   |   `-- ssh.rule_v6
|   `-- OUTPUT
|       `-- default
|-- mangle
|   |-- FORWARD
|   |   `-- default
|   |-- INPUT
|   |   `-- default
|   |-- OUTPUT
|   |   `-- default
|   |-- POSTROUTING
|   |   `-- default
|   `-- PREROUTING
|       `-- default
|-- nat
|   |-- OUTPUT
|   |   `-- default
|   |-- POSTROUTING
|   |   `-- default
|   `-- PREROUTING
|       `-- default
`-- raw
    |-- OUTPUT
    |   `-- default
    `-- PREROUTING
        `-- default

17 directories, 15 files

cat /etc/iptables/rules.v4
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
--append INPUT --protocol tcp --dport 22 -j ACCEPT
COMMIT
*raw
:OUTPUT ACCEPT [0:0]
:PREROUTING ACCEPT [0:0]
COMMIT
*nat
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:PREROUTING ACCEPT [0:0]
COMMIT
*mangle
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:PREROUTING ACCEPT [0:0]
COMMIT

cat /etc/iptables/rules.v6
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
--append INPUT --protocol tcp --dport 22 -j ACCEPT
COMMIT
*raw
:OUTPUT ACCEPT [0:0]
:PREROUTING ACCEPT [0:0]
COMMIT
*mangle
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:PREROUTING ACCEPT [0:0]
COMMIT

**Comment by aalmenar** [comment] 2016-10-06 16:51
Downloaded the repo and this test fails:

rake kitchen:lwrp-chain-create-default-ubuntu-1604

       # Running tests:

       iptables-ng::lwrp_chain_create_default#test_0001_should set default FORWARD policy to DROP = 0.00 s = F
       iptables-ng::lwrp_chain_create_default#test_0002_should enable iptables serices = 0.17 s = .
       iptables-ng::lwrp_chain_create_default#test_0003_should apply the specified iptables rules = 0.02 s = F


       Finished tests in 0.194298s, 15.4402 tests/s, 25.7337 assertions/s.

         1) Failure:
       iptables-ng::lwrp_chain_create_default#test_0001_should set default FORWARD policy to DROP [/var/chef/minitest/iptables_ng_test/lwrp_chain_create_default_test.rb:7]:
       Expected file '/etc/iptables.d/filter/FORWARD/default' to include the specified content


         2) Failure:
       iptables-ng::lwrp_chain_create_default#test_0003_should apply the specified iptables rules [/var/chef/minitest/iptables_ng_test/lwrp_chain_create_default_test.rb:17]:
       Expected "Chain INPUT (policy ACCEPT)\ntarget     prot opt source               destination         \n\nChain FORWARD (policy ACCEPT)\ntarget     prot opt source               destination         \n\nChain OUTPUT (policy ACCEPT)\ntarget     prot opt source               destination         \n" to include "Chain FORWARD (policy DROP)".

**Comment by chr4** [comment] 2016-10-06 16:58
Which version of the cookbook are you using? I'm using the exact same policy setting on multiple production machines on xenial using `2.3.1`.

The test should'nt fail, in case you're using current master, that needs to be fixed...

**Comment by chr4** [comment] 2016-10-06 17:00
Can you paste the output of `cat /etc/iptables.d/filter/INPUT/default`?

**Comment by aalmenar** [comment] 2016-10-06 17:25
cat /etc/iptables.d/filter/INPUT/default
ACCEPT [0:0]

**Comment by aalmenar** [comment] 2016-10-06 17:27
The version of the cookbook being use according to berkshelf is: Using iptables-ng (2.3.1)

Also the tests fail, i checked out the repo when i opened this issue and using master.

**Comment by chr4** [comment] 2016-10-06 17:29
I was able to reproduce the issue on one of my machines. I think you spotted something here, will look into it.

**Comment by chr4** [comment] 2016-10-06 17:35
I think https://github.com/chr4-cookbooks/iptables-ng/commit/476871e1db5385a7af12cc30776abebf92e646dc#diff-22c9e9950b290a03ab5b3160eea23c9dR55 introduced this. @sspans, can you comment on this?
It feels like the policy is not updated correctly since the exception workaround.

**Comment by chr4** [comment] 2016-10-07 08:47
The way Chef seems to be going right now (removing ressource-cloning) I think we have to die one of the two deaths.

In this specific term, maybe it would be best to force people to run the `install` recipe, so the default chain folders are created, and then force them to use `iptables_ng_chain` manually, in case they want to add custom chains, and remove the code creating the chains from the `iptables_ng_rule` provider.

**Comment by chr4** [comment] 2016-10-07 09:06
The problem of finding an unique ressource name for 476871e#diff-22c9e9950b290a03ab5b3160eea23c9dR55 persists, though.

**Comment by chr4** [comment] 2016-10-07 09:07
One solution (again, hurting convenience) is to remove setting the default policies in the`iptables-ng::install` recipe, and forcing the users to set them on their own. This is error prone, though I fear.

**Comment by chr4** [comment] 2016-10-07 09:29
Closing this in favor of [this pull-request](https://github.com/chr4-cookbooks/iptables-ng/pull/64)

**Closed by chr4** 2016-10-07 09:29 UTC
